services:
  apache:
    build: docker/apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/pokemon
    env_file:
      - ./.env
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
#  bind9:
#    build: ./bind
#    container_name: bind9
#    ports:
#      - "3053:53/udp"
#      - "3053:53/tcp"

volumes:
  mariadb_data: