services:
  apache:
    build: ./
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rt
      MYSQL_DATABASE: pokedex
      MYSQL_USER: phpstorm
      MYSQL_PASSWORD: p@ssw0rt
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"